### ISSUE TITLE
Please provide cmake files for build support

### ISSUE THREAD

**Issue by mbanck** [schrodinger/coordgenlibs#31]
RDKit uses coordgenlibs these days, though by default downloads and builds it itself.

Linux distributions like Debian/Ubuntu already ship coorgenlibs, but RDKit cannot find the system-installed version due to `find_package(coordgen MODULE)` not finding anything as there are no CMake files available and/or being installed.

So please ship cmake files.

**Comment by ricrogz** [comment]
Hi, @mbanck,

I see from the linked RDKit issue that you were looking at an older coordgenlibs release. I think the current one already includes the required exports so that it can be found by CMake.

Do you still have problems to find it on your system?

**Comment by d-b-w** [comment]
@mbanck -
I think that cmake files are already included in the installation since https://github.com/schrodinger/coordgenlibs/commit/dc39bc7c0b93e865e44e257f48a843aecd47eb73, which is available in the v1.3 release.

I'm going to close this issue, please reopen it or create a new one if you are still having trouble using `find_package()` with coordgen.
